# Generated by Django 5.0.6 on 2024-06-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=255)),
            ],
        ),
    ]
