# Generated by Django 5.0.6 on 2024-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0004_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
