# Generated by Django 5.0.6 on 2024-06-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0005_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
