# Generated by Django 5.0.6 on 2024-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0006_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
