# Generated by Django 5.0.6 on 2024-06-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0008_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
