# Generated by Django 5.0.6 on 2024-06-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0010_alter_borrowrecord_borrow_date_book_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
