# Generated by Django 5.0.6 on 2024-06-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0011_rename_book_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
