# Generated by Django 5.0.6 on 2024-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0012_remove_books_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
