# Generated by Django 5.0.6 on 2024-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0013_alter_books_options_books_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
