# Generated by Django 5.0.6 on 2024-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0015_cartitem_cart_delete_borrowrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
