# Generated by Django 5.0.6 on 2024-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0016_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ManyToManyField(to='elib.books'),
        ),
    ]
