# Generated by Django 5.0.6 on 2024-06-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0017_remove_cartitem_book_cartitem_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elib.books'),
        ),
    ]
