# Generated by Django 5.0.6 on 2024-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0018_remove_cartitem_book_cartitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
