# Generated by Django 5.0.6 on 2024-06-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0020_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elib.customer'),
        ),
    ]
