# Generated by Django 5.0.6 on 2024-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elib', '0023_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
